"""
MCTS strategy based on LLM probability distribution
"""

import numpy as np
from typing import List, Tuple, Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from lsda.llm_mcts.llm_prompts import LLMPromptEngine
    from lsda.scenario.envScenario import EnvScenario


class LLMProbabilityPolicy:
    """
    Use the probability distribution generated by LLM as MCTS prior strategy
    Simplified version: no observation space clipping, use complete observation space
    """
    
    def __init__(self, llm_engine: 'LLMPromptEngine', scenario: 'EnvScenario'):
        self.llm_engine = llm_engine
        self.scenario = scenario
        self.current_frame = 0
        self._cached_probabilities = None
        self._cache_frame = -1
        print("[blue]🔧 LLM Prior Policy: Using complete observation space without observation clipping[/blue]")
    
    def __call__(self, state, observation) -> Tuple[List[int], List[float]]:
        """
        Get action probability distribution
        Ensure only available actions are assigned probabilities
        
        :param state: Environment state
        :param observation: Observation data (complete observation space)
        :return: (actions, probabilities)
        """
        try:
            # Get available actions from environment, ensure unavailable actions don't get probability
            if hasattr(state, 'get_available_actions'):
                available_actions = list(state.get_available_actions())
            else:
                available_actions = list(range(state.action_space.n))
            
            print(f"[cyan]🎯 Available actions: {available_actions}[/cyan]")
            
            # Use cache to avoid repeated LLM calls
            if self._cache_frame == self.current_frame and self._cached_probabilities is not None:
                # Ensure cached probability distribution matches current available actions
                if len(self._cached_probabilities) == len(available_actions):
                    print(f"[cyan]🔄 Using cached action probabilities (frame={self.current_frame})[/cyan]")
                    return available_actions, self._cached_probabilities
            
            # Call LLM to get action probabilities using available actions from environment
            actions, probabilities, _ = self.llm_engine.get_action_probabilities(
                self.scenario, self.current_frame, available_actions,
                critical_vehicles=None,  # critical_vehicles parameter deprecated
                print_response=False
            )
            
            # Verify correctness of action probability distribution
            if len(actions) == len(available_actions) and set(actions) == set(available_actions):
                # LLM returned action matches environment available actions
                pass
            else:
                # If not matching, use uniform distribution over environment available actions
                print(f"[yellow]⚠️  LLM actions do not match environment, using uniform distribution[/yellow]")
                uniform_prob = 1.0 / len(available_actions)
                probabilities = [uniform_prob] * len(available_actions)
                actions = available_actions
            
            # Final verification: ensure unavailable actions have no probability
            assert len(actions) == len(probabilities), f"Action and probability length mismatch: {len(actions)} vs {len(probabilities)}"
            assert abs(sum(probabilities) - 1.0) < 1e-6, f"Probability sum is not 1: {sum(probabilities)}"
            assert set(actions) == set(available_actions), f"Actions mismatch: {actions} vs {available_actions}"
            
            # Cache result
            self._cached_probabilities = probabilities
            self._cache_frame = self.current_frame
            
            print(f"[green]✅ Action probability distribution: {dict(zip(actions, probabilities))}[/green]")
            return actions, probabilities
            
        except Exception as e:
            print(f"[red]❌ LLM probability policy failed: {e}[/red]")
            # Fall back to uniform distribution over environment available actions
            if hasattr(state, 'get_available_actions'):
                available_actions = list(state.get_available_actions())
            else:
                available_actions = list(range(state.action_space.n))
            
            uniform_prob = 1.0 / len(available_actions)
            return available_actions, [uniform_prob] * len(available_actions)
    
    def update_frame(self, frame: int):
        """Update the current frame number."""
        self.current_frame = frame


class LLMRolloutPolicy:
    """
    LLM-driven rollout policy (simplified), using a random strategy for performance.
    """
    
    def __init__(self, llm_engine: 'LLMPromptEngine', scenario: 'EnvScenario', use_probability: bool = False):
        self.llm_engine = llm_engine
        self.scenario = scenario
        self.use_probability = use_probability
        self.current_frame = 0
        print("[blue]🔧 LLM Rollout Policy: uniform over available actions[/blue]")
    
    def __call__(self, state, observation) -> Tuple[List[int], List[float]]:
        """
        Rollout policy using a uniform distribution over available actions,
        ensuring unavailable actions are never selected.
        """
        # Get available actions from environment
        if hasattr(state, 'get_available_actions'):
            available_actions = list(state.get_available_actions())
        else:
            available_actions = list(range(state.action_space.n))
        
        # Use uniform distribution for available actions, probability 0 for unavailable actions
        uniform_prob = 1.0 / len(available_actions)
        return available_actions, [uniform_prob] * len(available_actions)
    
    def update_frame(self, frame: int):
        """Update the current frame number."""
        self.current_frame = frame


def create_llm_policies(llm_engine: 'LLMPromptEngine', scenario: 'EnvScenario') -> Tuple[LLMProbabilityPolicy, LLMRolloutPolicy]:
    """
    Create LLM-driven MCTS policies.
    
    :param llm_engine: LLM prompt engine
    :param scenario: Scenario object
    :return: (prior_policy, rollout_policy)
    """
    prior_policy = LLMProbabilityPolicy(llm_engine, scenario)
    rollout_policy = LLMRolloutPolicy(llm_engine, scenario, use_probability=False)  # Rollout uses random strategy to maintain exploration
    
    return prior_policy, rollout_policy
